version: '3.7'
services:
  db:
    container_name: dmoj_mysql
    image: mariadb
    restart: always
    volumes:
      - ./database/:/var/lib/mysql/
    env_file: [environment/mysql.env, environment/mysql-admin.env]
    networks: [db]
  redis:
    container_name: dmoj_redis
    image: redis:alpine
    restart: always
    networks: [site]
  site:
    build: .
    image: zharaskhan/dmoj-base
    init: true
    restart: unless-stopped
    entrypoint: uwsgi --ini uwsgi.ini
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./media/:/media/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    depends_on: [db, redis]
  celery:
    image: zharaskhan/dmoj-base
    init: true
    restart: unless-stopped
    entrypoint: celery -A dmoj_celery worker -l info --concurrency=2
    volumes:
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - ./repo/:/site/
      - ./media/:/media/
      - ./problems/:/problems/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, db]
    depends_on: [db, redis]
  bridged:
    image: zharaskhan/dmoj-base
    init: true
    restart: unless-stopped
    entrypoint: python3 manage.py runbridged
    volumes:
      - pdfcache:/pdfcache/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    environment:
      - BRIDGED_JUDGE_ADDRESS=0.0.0.0
    networks: [site, nginx, db, judge]
    ports:
      - 127.0.0.1:9999:9999
    depends_on: [db, redis]
  nginx:
    container_name: dmoj_nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./media/:/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: [nginx]
    depends_on: [site]
  # texoid:
  #   build:
  #     context: .
  #     dockerfile: ./texoid/Dockerfile
  #   image: ninjaclasher/dmoj-texoid
  #   init: true
  #   restart: unless-stopped
  #   networks: [site]
  # pdfoid:
  #   build:
  #     context: .
  #     dockerfile: ./pdfoid/Dockerfile
  #   image: ninjaclasher/dmoj-pdfoid
  #   init: true
  #   restart: unless-stopped
  #   networks: [site]
  #   cap_add:
  #     - SYS_ADMIN
  # mathoid:
  #   build:
  #     context: .
  #     dockerfile: ./mathoid/Dockerfile
  #   image: ninjaclasher/dmoj-mathoid
  #   init: true
  #   restart: unless-stopped
  #   volumes:
  #     - ./mathoid/config.yaml:/node_modules/mathoid/config.yaml
  #   networks: [site]
  wsevent:
    build:
      context: .
      dockerfile: ./wsevent/Dockerfile
    image: ninjaclasher/dmoj-wsevent
    init: true
    restart: unless-stopped
    volumes:
      - ./repo/:/app/site/
    working_dir: /app/site
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx]
  judge:
    build: judge
    image: zharaskhan/dmoj-judge
    restart: unless-stopped
    ports:
      - 127.0.0.1:9998:9998
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./problems/:/problems/
    command: ["run", "-p", "9999", "-c", "/judge.yml", "bridged", "judge", "judge"]
    networks: [judge]
    depends_on: [bridged]
networks:
  site:
  db:
  nginx:
  judge:
volumes:
  assets:
  pdfcache:
  datacache:
  cache:
