version: '3.7'
services:
  db:
    container_name: dmoj_mysql
    image: mariadb
    restart: always
    volumes:
      - ./database/:/var/lib/mysql/
    env_file: [environment/mysql.env, environment/mysql-admin.env]
    networks: [db]
  redis:
    container_name: dmoj_redis
    image: redis:alpine
    restart: always
    networks: [site]
  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: zharaskhan/dmoj-base
    network_mode: none
  prod:
    build:
      context: .
      dockerfile: ./prod/Dockerfile
    image: zharaskhan/dmoj-prod
    network_mode: none
  site:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    image: zharaskhan/dmoj-site
    init: true
    restart: unless-stopped
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./media/:/media/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    depends_on: [base, db, redis]
  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    image: zharaskhan/dmoj-celery
    init: true
    restart: unless-stopped
    volumes:
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, db]
    depends_on: [base, db, redis]
  bridged:
    build:
      context: .
      dockerfile: ./bridged/Dockerfile
    image: zharaskhan/dmoj-bridged
    init: true
    restart: unless-stopped
    volumes:
      - pdfcache:/pdfcache/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    ports:
      - 9999:9999
    depends_on: [base, db, redis]
  nginx:
    container_name: dmoj_nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./media/:/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: [nginx]
    depends_on: [site]
networks:
  site:
  db:
  nginx:
volumes:
  assets:
  pdfcache:
  datacache:
  cache:
