name: Build Docker Images
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch: # This enables manual execution
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize submodules
        run: |
          git submodule update --init --recursive
      - name: Build images
        run: docker-compose build
        working-directory: dmoj
      - name: Test images
        run: |
          ./scripts/initialize
          docker-compose up -d
          sleep 10
          COMPOSE_EXEC_FLAGS="-T" ./scripts/copy_static
          COMPOSE_EXEC_FLAGS="-T" ./scripts/migrate
          COMPOSE_EXEC_FLAGS="-T" ./scripts/manage.py loaddata language_small
        working-directory: dmoj
      - name: Push images to Docker
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker push zharaskhan/dmoj-prod:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
